[gcp_service_account] 
type = "service_account"
project_id = "dbt-demos-392016"
private_key_id = "eb143eaf19f5242a604d66c3e73b18af89146e65"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4PZCHab9qWVjG
FphX/c3zEAUqSlalcDva2qNReZ1V4LJzjvv1K7/J6J6AmAWiS07Y6rOC3Mzv2J2l
SRtZlOvtYKbNIQk1e0BE1PZGheBlkbdSRkqcWfqa/wTq71A8Ncv+PNdVr7S1m4se
gbP4gJQLxIyVIh1rb/u3p9LM5nrKuZq/bNXk9NT1oef8xgzvlk0Coq36uVWW1Y/M
HhXrNUTLltnjKBUjUeXnRR6Rrh0QpZqoku298evdwr64WuRJl3VtaE7h2s4WZMz7
yeiUBSLkAQkxqrxn8XdZSQc+tdzTkwP3RcNX/mj4GTvoS8PI7IJSkmSF2pkuy3vu
514JWY85AgMBAAECggEACZcu1FW1YKBZBiq78GymUV5Gno5zFzaR7xENilq1zXge
YfSR+g+2cpi404HWXT3lU1ZYVNoQkvWoMyfslAu0Ak3TMP9kvtN1I4Agd8hVR4Q/
0jkVfjES4gmfZGljuFamkUvye6PjWMbJhaODzk5HJpurI8I8XNDd/g/u4bqnrrDH
EXhNg/MHaqWlGRqdeBB5+x+P8HMOjI9riHS5Hk4wygNlSOFerJAR+ietnpfG9VeS
ogx8+UTHG8kcCnjCYf3ZTGl6MpMnyZaBOxV7GOLrBON6zERC64KOlb5vwMvCyJJC
b/QCozVNbFLxyQKggjjtePVEg4BSJueITqjzrU5R+QKBgQDOnmIV3NrTfqR+UpOA
JuSqy9wbDLsx7P8OI94otdv1veW3xvBqi+8xOxooRSRC1/qztTSQ/bYODBnyzMqA
kcGPfv5f3Q3cop4yOVjpXAcl2k8sbTaC2SUOmE3IZN0HouVlXzP2g4RMRZAxbi10
w+CA9ucXI0KlN2V/fzXMfBFSRQKBgQDkRgJPJvCX8ea7cKm++PLqUfl77c4wTIcR
vnFCkImD3dcBmNkJVbT8BNqSxnL/se4tertyt+xLor4olr72hAC5c0obvSXp7hHO
+x5TkvCZz8OFNuLR+1iTzeyc5YPExNeQ/uqMF2FDjw0aif76WRjI+U+RUF8F/ya2
ElL0eSJSZQKBgDA1Phdxx1DPXJvosmeVK4c6N2nMR6T3ce8fqUcAX4jvvLhrX07M
xYtMCedZcoNyFxl07wXhXGfcpPVEmP70gx/y9nDxh7lx6802GiuggD5xuEVaWfyf
o4jLOmLGPdf5RuKnGt2qg+Sz2lfeKBb1WN1ePj7kyDj6OuFLkgba78OtAoGAYuEA
dxDC/s5Fx8ORg6uKbX18t/XWbo13pHP903uQVZJuY761pJl/f/sKQrG7do64QPL8
50BMFqcz/5jstxOOzMXnwAQ6vA3noOSdyk3H8phQdQ/FSHe7cqqsZ3nzjfRF/ASv
zGcENqNsZaaI0CBv3/4+PQ+3WX2gYxWk4UjnWRECgYEAnU8AWnTNJjQ+CMva7TM+
HWPubmbDwYz6bL3+bIhODye/nRbtn35Jxy6cVx9UPhia5EZB2jEZIuTHxOBqadTq
hs0l9kq3ouhuB1xmrYIRsAXlmulXnPClaZ8/OCTvMvgqFuoWfN/7FLJKYiTPQhgs
c2ZHhQUNnDTTuVHhgL7r2AU=
-----END PRIVATE KEY-----"""
client_email = "irungu-service-account@dbt-demos-392016.iam.gserviceaccount.com"
client_id = "109357433164906406856"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/irungu-service-account%40dbt-demos-392016.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

